### PR TITLE
chore: release 2.8.0

### PR DESCRIPTION
**Pull request by abhiabhi94**

### CODE REVIEW

**Comment by abhiabhi94** [comment]
build won't pass without merge and release of https://github.com/Radi85/sphinxcontrib-swagger/pull/1.

**Comment by Radi85** [comment]
@abhiabhi94 can you please update sphinxcontrib-swagger version?

**Comment by abhiabhi94** [comment]
> @abhiabhi94 can you please update sphinxcontrib-swagger version?

I re-ran the build, it automatically picked up the latest version since that wasn't pinned. 👯 .

**Review by Radi85 — APPROVED** [review]

**Comment by Radi85** [comment]
@abhiabhi94 don't we have a workflow for the main release? :thinking:

**Comment by abhiabhi94** [comment]
> @abhiabhi94 don't we have a workflow for the main release? thinking

we used to do a manual release to PyPI, and for test PyPI, they would be made once a tag is pushed on Github.

**Pull request merged**
