### PR TITLE
Change profile app name to resolve name conflics with ipython module

### LINKED ISSUE #11: The name of the profile application conflicts with the profile module in IPython
I currently have set the environment variable 
```bash
PYTHONBREAKPOINT=ipdb.set_trace
```
While adding a breakpoint for (debugging purposes) somewhere inside the `example` application, I get this error trace
```bash
Internal Server Error: /second-post/
Traceback (most recent call last):
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'Comment' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/library.py", line 234, in render
    return t.render(new_context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 986, in render
    output = self.filter_expression.resolve(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 670, in resolve
    obj = self.var.resolve(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 795, in resolve
    value = self._resolve_lookup(context)
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/Django-3.0.6-py3.7.egg/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/curious/Dev/opensourceDev/Comment/comment/models/comments.py", line 58, in likes
    breakpoint()
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/ipdb/__init__.py", line 7, in <module>
    from ipdb.__main__ import set_trace, post_mortem, pm, run             # noqa
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/ipdb/__main__.py", line 15, in <module>
    from IPython import get_ipython
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 28, in <module>
    from IPython.core.magics import (
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/IPython/core/magics/__init__.py", line 21, in <module>
    from .execution import ExecutionMagics
  File "/home/curious/.virtualenvs/comment/lib/python3.7/site-packages/IPython/core/magics/execution.py", line 24, in <module>
    import cProfile as profile
  File "/usr/lib/python3.7/cProfile.py", line 22, in <module>
    run.__doc__ = _pyprofile.run.__doc__
AttributeError: module 'profile' has no attribute 'run'
[12/May/2020 22:24:49] "GET /second-post/ HTTP/1.1" 500 469180
```
From what I could see in the stack trace, `ipython` is trying is to search for a module `profile` but this fails as we have a django application with this name. 
This could be easily solved by changing the name of the application to something like `user_profile` and making other corresponding changes. 
If it's okay, I will fix this after we finish up adding reactions to the application.

### PR DESCRIPTION
**Pull request by abhiabhi94**
- make other corresponding changes
- fixes #11 

Change some imports order to follow PEP8 conventions.

### CODE REVIEW

**Comment by Radi85** [comment]
Thanks again for your efforts. The changes looks good.
I can see this conflict now. You can add this file to .gitignore to avoid such conflict in the future.

**Comment by abhiabhi94** [comment]
> Thanks again for your efforts. The changes looks good.

Hey Radi, thanks for the application first of all. I liked the application because most of the other django application for comments were using POST requests to post comments.

**Comment by Radi85** [comment]
@abhiabhi94, Shall you fix the conflict?

**Comment by abhiabhi94** [comment]
I have added the file to `.gitignore` and removed it from my git index using the command: 
```
git rm --cached test/db.sqlite3
```
This should be sufficient in general. But it apparently isn't somehow. What more should I do?

**Comment by Radi85** [comment]
> I have added the file to `.gitignore` and removed it from my git index using the command:
> 
> ```
> git rm --cached test/db.sqlite3
> ```
> 
> This should be sufficient in general. But it apparently isn't somehow. What more should I do?

I have rebased and fixed the conflict in #13, I didn't merge directly with master just to ensure that coverage and build will pass.

**Pull request closed without merging**
