### PR TITLE
 Remove information about advanced usage from readme

### PR DESCRIPTION
**Pull request by abhiabhi94**
- instead give the link to documentation.
- add contributing instructions.
- also correct syntax highlighting for confirm comment view in web API documentation.

### CODE REVIEW

**Comment by abhiabhi94** [comment]
Also, I was thinking was removing the details mentioned in the `readme` and mention the link to read the doc documentation there. The instruction on how to add this application to`django` to get started would still remain there. This will help us in maintaining the documentation at only one place in the codebase.

**Comment by Radi85** [comment]
> Also, I was thinking was removing the details mentioned in the `readme` and mention the link to read the doc documentation there. The instruction on how to add this application to`django` to get started would still remain there. This will help us in maintaining the documentation at only one place in the codebase.

I was thinking of the same yesterday. I would keep the get started section with the example and move the rest to docs.

**Comment by Radi85** [comment]
Shall you cover this in this PR?

**Comment by abhiabhi94** [comment]
okay will do as you say, but you will have to wait for some time maybe 3-4 hours.

**Comment by Radi85** [comment]
> okay will do as you say, but you will have to wait for some time maybe 3-4 hours.

Sure. Take your time and do it whenever you like. We are not in hurry 😄

**Pull request merged**
