### PR TITLE
Fix links in the readme

### PR DESCRIPTION
**Pull request by abhiabhi94**
- relative links don't work in the readme for PyPi, hence make all links made absolute.
- also add documentation regarding usage of gravatars.
- fix possible grammatical error in readme.

### CODE REVIEW

**Comment by abhiabhi94** [comment]
The link seems to be working as of writing this : https://pepy.tech/project/django-comments-dab/month

[Downloads](https://pepy.tech/project/django-comments-dab/month)

Attaching a screenshot, if the link doesn't work again :)

Screenshot

**Comment by Radi85** [comment]
> The link seems to be working as of writing this : https://pepy.tech/project/django-comments-dab/month
> 

Feel free to use this instead of the exisitng one. Please don't forget to update the docs as well.

**Comment by abhiabhi94** [comment]
>  Please don't forget to update the docs as well.

regarding?

**Comment by Radi85** [comment]
> regarding?
 download badge

**Comment by abhiabhi94** [comment]
I looked up at a couple of the other libraries and most of them use the link which we are using currently. Till i get the time to get into the detail of the methodology used by the two different links, i think we can continue using the current link.

**Review by Radi85 — APPROVED** [review]

**Pull request merged**
