### PR TITLE
chore: translate the persian language (fa) 

### PR DESCRIPTION
**Pull request by AmirAref**

### CODE REVIEW

**Comment by Radi85** [comment]
@AmirAref thanks for your contribution, can you squash your commits according to https://github.com/Radi85/Comment/blob/develop/CONTRIBUTING.rst#pr-and-commit-messages

**Comment by AmirAref** [comment]
@Radi85 hi, now I squashed the commits

**Comment by AmirAref** [comment]
@Radi85 what happend to this pr?

**Review by abhiabhi94 — APPROVED** [review]
just cross checked a few using google translate, looks fine to me.

Thanks for taking the time to contribute 🎉  , look forward to seeing more from you :).

**Comment by Radi85** [comment]
> @Radi85 what happend to this pr?

Hello @AmirAref ,

There was an issue in the pipeline and it's now fixed, can you please rebase your PR?

**Pull request merged**
