### PR TITLE
feat(#153): Add support for rendering content in markdown format

### LINKED ISSUE #153: Add support for rendering comment in markdown format
### Proposed Functionality
I think we can probably use a template tag with the help of a third-party package to render comment content in `markdown` format. Comment truncation should be disabled when this functionality is enabled.

### Use Case
Adds highlighting of codes and other stuff.

### Database Changes
None.

### PR DESCRIPTION
**Pull request by abhiabhi94**
resolves #153

### CODE REVIEW

**Comment by abhiabhi94** [comment]
The test failures from `travis` seem weird to me at the moment. 😞 

 `tox` passes locally for me. Seeing the logs, I think the `tests` are probably not being run on the latest version of this branch.

**Comment by abhiabhi94** [comment]
okay, got it the test failures are from Django `2.1`, didn't run `tox` locally on it. 

So the failures on `2.1` is due to the [bug](https://code.djangoproject.com/ticket/31128) and has been fixed in https://code.djangoproject.com/ticket/31128 on `3.2`. It was also back ported to `3.1` but not to `2.1` and `2.2`.

**Comment by abhiabhi94** [comment]
Hey @Radi85, how are you?

This has been stagnant for a long time. I just updated this branch with the `main` branch. In case, you have some time, it would be great to have your review on this.

**Review by Radi85 — APPROVED** [review]
Hey @abhiabhi94, Thanks a lot for your good work!

**Pull request merged**
