### PR TITLE
chore: Add tests for exceptions module

### PR DESCRIPTION
**Pull request by abhiabhi94**

### CODE REVIEW

**Comment by Radi85** [comment]
@abhiabhi94,
I would you like to add you as a maintainer with your email in pyp,i if you don't mind, can you please send me your email?

**Comment by abhiabhi94** [comment]
I have an account with the username `tinkerer` on pypi. Will it work that way?

If it doesn't work that I will email you from mine.  In general, I don't know why I just don't want like to expose my email to the public although it is available at so many job portals these days. :-p

**Comment by Radi85** [comment]
No worries.
I will try to use your username.

**Comment by Radi85** [comment]
@abhiabhi94,
Unfortunately didn't work with username or at least I didn't know how 😅 
However, feel free to add yourself as maintainer to PYPI whenever you wish.

**Comment by abhiabhi94** [comment]
> @abhiabhi94,
> Unfortunately didn't work with username or at least I didn't know how 😅
> However, feel free to add yourself as maintainer to PYPI whenever you wish.

i will email you directly.

**Comment by Radi85** [comment]
I got it.
But your email will be public 😄

**Comment by abhiabhi94** [comment]
no issues...as it is privacy is a myth :-p

**Comment by Radi85** [comment]
Hmmm, I invited you to the project with your username only. I should have used PYPI GUI to do that but I was thinking to add the maintainers to `setup.py`

**Comment by abhiabhi94** [comment]
> Hmmm, I invited you to the project with your username only. I should have used PYPI GUI to do that but I was thinking to add the maintainers to `setup.py` and this didn't work.

I have a project where I have only added an `author_name` and give an empty string for `author_email`. It just gives me a  warning there `author email should be provided when the author name is given`. Does this sort of thing work with maintainer as well?

**Comment by abhiabhi94** [comment]
Also, I forgot and I am sorry. I should have asked for your permission before emailing you.

**Comment by Radi85** [comment]
> I have a project where I have only added an `author_name` and give an empty string for `author_email`. It just gives me a warning there `author email should be provided when the author name is given`. Does this sort of thing work with maintainer as well?

based on this answer https://stackoverflow.com/questions/9999829/how-to-specify-multiple-authors-emails-in-setup-py setup.py doesn't support list, instead using comma separated string and the result as shown here which I don't like.
Screenshot 2020-12-05 at 16 24 15

**Comment by Radi85** [comment]
> Also, I forgot and I am sorry. I should have asked for your permission before emailing you.

Come on. If I need to give permission to whoever wants to email me, I would never create an email 😄
Second, the privacy is a lie for most cases, once your email is used in one public service, magically will be exposed to everyone.

**Pull request merged**
