### PR TITLE
Add mixin to test content type and parent_id parameters from the URL

### PR DESCRIPTION
**Pull request by abhiabhi94**
- this works for both django and DRF.
- remove permissions that worked as mixin earlier for these parameters in drf, also corrects status code for wrong request to 400 from 403 in drf.
- add a module for testing mixin.
- add some other utility functions.

### CODE REVIEW

**Comment by Radi85** [comment]
Hi @abhiabhi94,

I am actually working on the same issue :( I didn't know that you are doing the same. I didn't finish yet but I think I will merge this and rebase my work on it and refactor both codes accordingly. Please consider opnening a new issue before start wroking on it :)

**Comment by abhiabhi94** [comment]
> I am actually working on the same issue :( I didn't know that you are doing the same. I didn't finish yet but I think I will merge this and rebase my work on it and refactor both codes accordingly. Please consider opnening a new issue before start wroking on it :)

Yes surely from now on will keep this in mind. If I remember I had told I will factor this after the closing of anonymous comments but you're right making an issue would be more apt.

**Comment by abhiabhi94** [comment]
Also, is there something that you would want me to work upon currently, apart from adding documentation for testing sending of email and other changes to documentation.

Also, I'll try to refactor and move all functions receiving signals to a separate module `listeners.py` if i get the time today.

**Comment by Radi85** [comment]
> Also, is there something that you would want me to work upon currently?

What about #43?

> Also, I'll try to refactor and move all functions receiving signals to a separate module `listeners.py` if i get the time today.

I was thinking of this but didn't have time. Please name the module `signals.py` instead.

> I have adding documentation for testing sending of email and other changes to documentation, in the pipeline after that.

Great!

I was thinking of releasing a new version by tomorrow, I hope I will have enough time for that, otherwise would be next week.
PS: #43 should be in the next release not this one.

**Pull request merged**
